### ISSUE TITLE
Update `community-hub-release-parent` POM to 1.3.1

### ISSUE THREAD

**Issue by xomiamoore** [camunda-community-hub/camunda-platform-7-grpc-external-task#63]
For folks using the `community-hub-release-parent` POM, an update is required because we recently moved from Nexus to Artifactory [(learn more here).](https://camunda.com/blog/2022/03/a-new-domain-name-for-camunda-artifactory/) Please make sure you are using **[version 1.3.1](https://github.com/camunda-community-hub/community-hub-release-parent)** to avoid failed deployments.

**Comment by tmetzke** [comment]
Done with [5577280](https://github.com/camunda-community-hub/camunda-platform-7-grpc-external-task/commit/5577280aa7332f27b6f6a018368ecfc6d3f8dabb)
